### PR TITLE
Use synchronous API

### PR DESCRIPTION
**Pull request by gottscj**
This is a bit disruptive I know, but I was experiencing deadlocks and as all db calls where used sync anyway I changed to use the sync API Mongo added for 2.2.3. This resolves the deadlocks, improves readability and actually boosts performance.

### CODE REVIEW

**Comment by sergeyzwezdin** [comment]
How to reproduce deadlocks?

**Comment by gottscj** [comment]
Disclaimer: Im guessing its some sort of deadlock.

This is a vanilla Console app with latest MongoDB nuget, latest Hangfire.Core nuget and latest Hangfire.Mongo nuget.

this is my Program.Main:
`class Program
	{
		static void Configure(IAppBuilder app)
		{
			LogProvider.SetCurrentLogProvider(new ColouredConsoleLogProvider());
			GlobalConfiguration.Configuration.UseMongoStorage("mongodb://localhost:30000", "testjobs");
			app.UseHangfireServer();
			app.UseHangfireDashboard();
		}
		static void Main(string[] args)
		{
			using (WebApp.Start("http://localhost:8080", Configure))
			{
				var sw = Stopwatch.StartNew();

				RecurringJob.AddOrUpdate(() => Console.WriteLine("Job 1"), Cron.Minutely);
				RecurringJob.AddOrUpdate(() => Console.WriteLine("Job 2"), Cron.Minutely);
				RecurringJob.AddOrUpdate(() => Console.WriteLine("Job 3"), Cron.Minutely);
				Console.WriteLine("Started 3 jobs in {0} ms", sw.ElapsedMilliseconds);
				sw.Stop();
				Console.ReadLine();
			}
		}
	}`

This is the print in Console: "Started 3 jobs in 31277 ms" 

If I change to my fork the print is: "Started 3 jobs in 949 ms" 

I can send you the zip of my Console app if you like.

Thanks,
Jonas

**Comment by sergeyzwezdin** [comment]
Thanks for explanation. I'll taike a look a bit later.

**Comment by tristal** [comment]
@sergeyzwezdin -- this is identical to the PR I sent a while back (https://github.com/sergeyzwezdin/Hangfire.Mongo/pull/24).  We have been running my fork in production for a month or so and have not seen a hang/deadlock since.  Until the code was deployed, we were having to restart our Hangfire instances daily.

**Comment by gottscj** [comment]
It seems that the waiting happens in "MongoWriteOnlyTransaction", especially in "SetRangeInHash" and "AddToSet". I havent figured out why this is happening yet. 

My traces:
Executed command SetRangeInHash in 503 ms
Executed command SetRangeInHash in 2808 ms
Executed command SetRangeInHash in 13004 ms
Executed command SetRangeInHash in 1047 ms
Executed command AddToSet in 945 ms
Executed command SetRangeInHash in 2 ms
Executed command SetRangeInHash in 46 ms
Executed command SetRangeInHash in 3 ms
Executed command SetRangeInHash in 1 ms
Executed command AddToSet in 2 ms
Executed command SetRangeInHash in 5 ms
Executed command SetRangeInHash in 157 ms
Executed command SetRangeInHash in 4 ms
Executed command SetRangeInHash in 3 ms
Executed command AddToSet in 2 ms
Added 3 jobs in 19008 ms

**Comment by sergeyzwezdin** [comment]
Ok, let's try to use sync API until Hangfire will have async API for data storage.
Can I ask you to update PR to have no conflicts and all tests green?

**Comment by gottscj** [comment]
Off course! I'll fix it first thing Monday. :)

**Comment by gottscj** [comment]
I took the liberty of adding an xunit  runner to the project also. I will remove it you dont want it as part of the commit.

Thanks

**Comment by gottscj** [comment]
Hi,

Did you change your mind on this? :)

Thanks,
Jonas

**Comment by sergeyzwezdin** [comment]
@gottscj thanks for PR

**Pull request merged**
