### PR TITLE
Fix FormatException Issue

### PR DESCRIPTION
**Pull request by peterdamm**
Hangfire.Mongo runs the isMaster Command on MongoDB, to get the local time from the database.
Depeding on the result, this may cause a FormatException in the MongoDb.Driver.

Response that works:
```
{
	"ismaster" : true,
	"maxBsonObjectSize" : 16777216,
	"maxMessageSizeBytes" : 48000000,
	"maxWriteBatchSize" : 1000,
	"localTime" : ISODate("2016-02-19T13:03:25.244Z"),
	"maxWireVersion" : 4,
	"minWireVersion" : 0,
	"ok" : 1
}
```

Response that causes FormatException:
```

{
        "hosts" : [
                "ob1.fus.cated:27017",
                "ob2.fus.cated:27017"
        ],
        "setName" : "replicaset1",
        "setVersion" : 2,
        "ismaster" : true,
        "secondary" : false,
        "primary" : "ob1.fus.cated:27017",
        "me" : "ob1.fus.cated:27017",
        "electionId" : ObjectId("56c45d823d4404a3b330555d"),
        "maxBsonObjectSize" : 16777216,
        "maxMessageSizeBytes" : 48000000,
        "maxWriteBatchSize" : 1000,
        "localTime" : ISODate("2016-02-19T13:07:36.218Z"),
        "maxWireVersion" : 4,
        "minWireVersion" : 0,
        "ok" : 1
}
```

As a fix this commit catches FormatExceptions caused during the command execution and returns the servers time instead.

### CODE REVIEW

**Comment by sergeyzwezdin** [comment]
Thank you for contributing.

I don't understand what the wrong in your response? Could you share exception details?

**Comment by sergeyzwezdin** [comment]
Do you think it's worth to check type of `localTime` variable as well?

**Comment by peterdamm** [comment]
Hi Sergey,

here is a detailed stacktrace:
```
[FormatException: ObjectSerializer does not support BSON type 'Timestamp'.]
   MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args) +898
   MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer`1 serializer, BsonDeserializationContext context) +154
   MongoDB.Bson.Serialization.Serializers.DynamicDocumentBaseSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args) +361
   MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args) +49
   MongoDB.Bson.Serialization.Serializers.ObjectSerializer.DeserializeDiscriminatedValue(BsonDeserializationContext context, BsonDeserializationArgs args) +318
   MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args) +504
   MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer`1 serializer, BsonDeserializationContext context) +154
   MongoDB.Bson.Serialization.Serializers.DynamicDocumentBaseSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args) +361
   MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args) +49
   MongoDB.Bson.Serialization.Serializers.ObjectSerializer.DeserializeDiscriminatedValue(BsonDeserializationContext context, BsonDeserializationArgs args) +318
   MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args) +504
   MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize(IBsonSerializer`1 serializer, BsonDeserializationContext context) +154
   MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply) +1738
   MongoDB.Driver.Core.WireProtocol.<ExecuteAsync>d__11.MoveNext() +1164
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.ConfiguredTaskAwaiter.GetResult() +28
   MongoDB.Driver.Core.Servers.<ExecuteProtocolAsync>d__26`1.MoveNext() +574
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.ConfiguredTaskAwaiter.GetResult() +28
   MongoDB.Driver.Core.Operations.<ExecuteProtocolAsync>d__29.MoveNext() +924
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.ConfiguredTaskAwaiter.GetResult() +28
   MongoDB.Driver.Core.Operations.<ExecuteAsync>d__2.MoveNext() +1033
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.ConfiguredTaskAwaiter.GetResult() +28
   MongoDB.Driver.<ExecuteReadOperationAsync>d__1`1.MoveNext() +460
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.ConfiguredTaskAwaiter.GetResult() +28
   MongoDB.Driver.<ExecuteReadOperationAsync>d__32`1.MoveNext() +557
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
   Hangfire.Mongo.Helpers.AsyncHelper.RunSync(Func`1 func) +191
   Hangfire.Mongo.MongoUtils.MongoExtensions.GetServerTimeUtc(IMongoDatabase database) +139
   Hangfire.Mongo.MongoUtils.MongoExtensions.GetServerTimeUtc(HangfireDbContext dbContext) +58
   Hangfire.Mongo.MongoMonitoringApi.GetHourlyTimelineStats(HangfireDbContext connection, String type) +211
   Hangfire.Mongo.MongoMonitoringApi.<HourlySucceededJobs>b__67(HangfireDbContext connection) +48
   Hangfire.Mongo.MongoMonitoringApi.UseConnection(Func`2 action) +52
   Hangfire.Mongo.MongoMonitoringApi.HourlySucceededJobs() +76
   Hangfire.Dashboard.Pages.HomePage.Execute() +357
   Hangfire.Dashboard.RazorPage.TransformText(String body) +68
   Hangfire.Dashboard.RazorPage.ToString() +38
   Hangfire.Dashboard.RazorPageDispatcher.Dispatch(RequestDispatcherContext context) +209
   Hangfire.Dashboard.<>c__DisplayClass8.<UseHangfireDashboard>b__4(IDictionary`2 env) +529
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +491
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +287
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +272
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.Rethrow() +33
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +150
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +42
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +380
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
```

I wonder which of the document field is of type 'Timestamp' and why that shoul differ between the two responses.

**Comment by sergeyzwezdin** [comment]
Are you running this code on same mongo instance?

**Comment by sergeyzwezdin** [comment]
Could you try to reproduce it with simple console app?

Code would be something like this:

```csharp
var client = new MongoClient("mongodb://localhost");
var db = client.GetDatabase("Test");
var result = db.RunCommand<dynamic>(new BsonDocument("isMaster", 1));
var dictionary = (IDictionary<string, object>)result;
Console.WriteLine(dictionary["localTime"].GetType());
```

In my case result is `DateTime`. What it returns on your machine? May be you can find cases when it isn't DateTime?

**Comment by peterdamm** [comment]
On my local mongo instance there occurs no exception and the response (tested in mongo shell) is the first one from my opening post.

On a deployed mongo cluster of a current project the format exception occurs and the response (tested in mongo shell) is the second one from my opening post.

I think reprodrucing with the console app would not help here, as the format exception would be thrown on RunCommand. But I could test the outcome on monday.

I think this is an issue that should be reported to the https://github.com/mongodb/mongo-csharp-driver
project, as RunCommand should succeed regardless of the result types, right?

**Comment by peterdamm** [comment]
I just tried to reproduce the problem with a simple console application.

The result is as expected:

On my local mongo instance the returned type is DateTime.

On the projects deployed mongo cluster the FormatException is thrown on Run Command, here is the Stacktrace:

```
System.FormatException was not handled.
  HResult=-2146233033
  Message=ObjectSerializer does not support BSON type 'Timestamp'.
  Source=MongoDB.Bson
  StackTrace:
       at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
       at MongoDB.Bson.Serialization.Serializers.DynamicDocumentBaseSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.DeserializeDiscriminatedValue(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
       at MongoDB.Bson.Serialization.Serializers.DynamicDocumentBaseSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.DeserializeDiscriminatedValue(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
       at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
       at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)
       at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
       at MongoDB.Driver.Core.Servers.ClusterableServer.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
       at MongoDB.Driver.Core.Servers.ClusterableServer.ServerChannel.Command[TResult](DatabaseNamespace databaseNamespace, BsonDocument command, IElementNameValidator commandValidator, Func`1 responseHandling, Boolean slaveOk, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
       at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ServerDescription serverDescription, ReadPreference readPreference, CancellationToken cancellationToken)
       at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ReadPreference readPreference, CancellationToken cancellationToken)
       at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
       at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
       at MongoDB.Driver.MongoDatabaseImpl.ExecuteReadOperation[T](IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
       at MongoDB.Driver.MongoDatabaseImpl.RunCommand[TResult](Command`1 command, ReadPreference readPreference, CancellationToken cancellationToken)
       at Hangfire.Mongo.FormatExceptionSample.Program.Main(String[] args) in c:\Projekte\Repositories\Git\Hangfire.Mongo.FormatExceptionSample\Hangfire.Mongo.FormatExceptionSample\Hangfire.Mongo.FormatExceptionSample\Program.cs:Zeile 33.
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by rolfwessels** [comment]
I'm getting the same issue.

**Nuget packages**
``` 
  <package id="Hangfire.Core" version="1.6.17" targetFramework="net45" />
  <package id="Hangfire.Mongo" version="0.5.7" targetFramework="net45" />
```

**Error stack trace**:

```
2018-01-10 12:04:48,647 DEBUG [(null)] - Error occurred during execution of 'BackgroundProcessingServer' process. Execution will be retried (attempt 1 of 2147483647) in 00:00:00 seconds.
System.FormatException: ObjectSerializer does not support BSON type 'Timestamp'.
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.Serializers.DynamicDocumentBaseSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.DeserializeDiscriminatedValue(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.Serializers.DynamicDocumentBaseSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.DeserializeDiscriminatedValue(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.Serializers.DynamicDocumentBaseSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.SerializerBase`1.MongoDB.Bson.Serialization.IBsonSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.DeserializeDiscriminatedValue(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](DatabaseNamespace databaseNamespace, BsonDocument command, IElementNameValidator commandValidator, Func`1 responseHandling, Boolean slaveOk, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ServerDescription serverDescription, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteReadOperation[T](IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.RunCommand[TResult](Command`1 command, ReadPreference readPreference, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoUtils.MongoExtensions.GetServerTimeUtc(IMongoDatabase database)
   at Hangfire.Mongo.MongoConnection.AnnounceServer(String serverId, ServerContext context)
   at Hangfire.Server.BackgroundProcessingServer.Hangfire.Server.IBackgroundProcess.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```

Works on dev machines and on staging but fails on production.

**Is master output:**
```{ 
    "hosts" : [
        "hangfireisawesome03:27017", 
        "hangfireisawesome04:27017"
    ], 
    "arbiters" : [
        "hangfireisawesome05:27017"
    ], 
    "setName" : "rs0", 
    "setVersion" : 7.0, 
    "ismaster" : true, 
    "secondary" : false, 
    "primary" : "hangfireisawesome03:27017", 
    "me" : "hangfireisawesome03:27017", 
    "electionId" : ObjectId("7fffffff0000000000000034"), 
    "lastWrite" : {
        "opTime" : {
            "ts" : Timestamp(1515582900, 1), 
            "t" : NumberLong(52)
        }, 
        "lastWriteDate" : ISODate("2018-01-10T11:15:00.000+0000")
    }, 
    "maxBsonObjectSize" : 16777216.0, 
    "maxMessageSizeBytes" : 48000000.0, 
    "maxWriteBatchSize" : 1000.0, 
    "localTime" : ISODate("2018-01-10T11:15:01.333+0000"), 
    "maxWireVersion" : 5.0, 
    "minWireVersion" : 0.0, 
    "readOnly" : false, 
    "ok" : 1.0
}
```

**Mongo version**
```{ 
    "version" : "3.4.9", 
    "modules" : [

    ], 
    "allocator" : "tcmalloc", 
    "javascriptEngine" : "mozjs", 
    "sysInfo" : "deprecated", 
    "versionArray" : [
        NumberInt(3), 
        NumberInt(4), 
        NumberInt(9), 
        NumberInt(0)
    ], 
    "openssl" : {
        "running" : "OpenSSL 1.0.2g  1 Mar 2016", 
        "compiled" : "OpenSSL 1.0.2g  1 Mar 2016"
    }, 
    "buildEnvironment" : {
        "distmod" : "ubuntu1604", 
        "distarch" : "x86_64", 
.....
        "target_os" : "linux"
    }, 
    "bits" : NumberInt(64), 
    "debug" : false, 
    "maxBsonObjectSize" : NumberInt(16777216), 
    "storageEngines" : [
        "devnull", 
        "ephemeralForTest", 
        "mmapv1", 
        "wiredTiger"
    ], 
    "ok" : 1.0
}
```

**Pull request merged**
