### PR TITLE
Updated MongoDistributedLock to use atomic operations

### PR DESCRIPTION
**Pull request by MarLoe**
Also made it thread safe so a lock can be acquired multiple times from the same thread.
Updated/added unit tests accordingly.

### CODE REVIEW

**Comment by sergeyzwezdin** [comment]
@MarLoe thank you for your contribution!
I have some thoughts and wanted to discuss with you. Unfortunately, I didn't find your contacts, so could you drop me message to sergey@zwezdin.com?

**Comment by pieceofsummer** [comment]
There's still a fundamental flaw in distributed lock, but it is hidden because of incorrect unit test `Ctor_ThrowsAnException_WhenResourceIsLocked`. `Task.Run` really starts a new task, but original task waits for its completion, hence there's actually only one task running. Since the child task "inherits" the lock, it should also "inherit" indication of the locked state.

That's why local storage should be not `ThreadLocal`, but `AsyncLocal` instead.

**Comment by MarLoe** [comment]
@pieceofsummer thank you for your input.

I am not sure that I really understand your notion of the lock state being "inherited".
If you replace the distributed lock with a "normal" lock in a unit test with the same structure, the expected behavior is the same. Please try the unit test in the bottom of the comment.

Also, I am leaning towards the HangfireIO/Hangfire implementation of [SqlServerDistributedLock.cs](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerDistributedLock.cs). I am not saying this implementation is right, but at least this implementation is consistent with the SqlServer implementation written be Mr. Hangfire himself.

```
        [Fact]
        public void Wait_TimesOut_WhenAlreadyLocked()
        {
            var theLock = new object();
            lock (theLock)
            {
                Assert.False(Task.Run(() =>
                    {
                        lock (theLock)
                        {
                            Assert.True(true, "Did not expect to acquire the lock");
                        }
                    }
                ).Wait(5000), "Expected the wait to timeout");
            }
        }
```

**Comment by pieceofsummer** [comment]
@MarLoe what I'm saying is, lock (by definition) should guard resources inside it's scope from being accessed concurrently. In the past only threads could produce concurrent access, hence it is a common knowledge that locks are used for cross-thread synchronization. 

But that's all history now. Current technologies operate even smaller units of work (e.g. tasks), which tend to randomly switch threads they're running on, making life even more interesting :)

Consider the following code:
```c#
[Fact]
public async Task Test_ThreadId()
{
    int threadId = Thread.CurrentThread.ManagedThreadId;
    await Task.Yield();
    Assert.Equal(threadId, Thread.CurrentThread.ManagedThreadId); // False!
}
```

Now, we'll go a little further:
```c#
private static ThreadLocal<int> __threadLocal = new ThreadLocal<int>();

[Fact]
public async Task Test_ThreadLocal()
{
    __threadLocal.Value = 123;
    await Task.Yield();
    Assert.Equal(123, __threadLocal.Value); // Also false!
}
```

Since the whole point of a distributed lock is to run only one instance of a (propbably heavy and long-running) task, the final scenario will look like:
```c#
[Fact]
public async Task Test_GuardedTask()
{
    using (var database = ConnectionUtils.CreateConnection())
    using (var @lock = new MongoDistributedLock("lock", TimeSpan.FromSeconds(1), database, new MongoStorageOptions()))
    {
        await Task.Run(async () =>
        {
            // .. more tasks
            await Task.Yield();
            // .. and more
        });
        // ... and even more tasks yet to do ...
    }
} 

For reference, a standard `lock` instruction (precisely because being thread-bound) won't allow `await` instructions inside its block. But since distributed lock is a bit more advanced synchronization primitive than a trivial mutex, it **should** support scenarios like these.

At this point you should know that you cannot use `ThreadLocal` values for storing lock state. And it turns out that Hangfire's `SqlServerDistributedLock` also misuses thread locals.

It works somehow while using a synchronous execution, (but still will fail if used from async child tasks), but it all would break the very moment Hangfire turns async.

**Comment by MarLoe** [comment]
@pieceofsummer thank you for clarifying. I am doing some updates to Hangfire.Mongo atm, and I will take your suggestion into account. Stay tuned :)

**Comment by pieceofsummer** [comment]
@MarLoe by the way, have you tested latency of the current implementation of  `MongoDistributedLock`? 

I have my own implementation (async-aware from the start, and also using events for signalling about lock state changes instead of just sleeping in a loop), and I'm curious if that will somewhat noticeably improve the processing throughput.

**Comment by MarLoe** [comment]
@pieceofsummer I hear you. I also hate "busy-waiting" like done in loop with sleep. But there are two arguments for doing so.

1. We have to! Since we cannot be signaled from other Hangfire instances on other machines, we need to poll the DB from time to time while waiting for the lock. I am currently not aware of a mechanism that allows us to be notified from mongo when a collection (or even a document) is updated.
2. Since we need to poll, we need a strategy for how often we poll. As I understand @sergeyzwezdin original intentions, he divides the total timeout into equally sized chunks (10 currently). The idea being that the greater the timout the more flexible is the user of the lock is to when it is acquired. So instead of polling e.g. 10 times a second, lesser load on mongo is prioritized with the implemented strategy.

When that is said, I also recognize that most running implementations most likely runs on one machine with one instance of Hangfire, making it a good suggestion to combine polling with some signalling.

**Comment by pieceofsummer** [comment]
@MarLoe yeah, you're right.

Though MongoDB can notify about changes, it requires OpLog feature to be enabled on server (disabled for most single-server installations, and has some specifics for sharded/failover cases), so it's not really an option.

I've made some changes to my implementation:
- Replaced `Heartbeat` timestamp with `ExpireAt` timestamp. Since different clients may use different `DistributedLockTimeout`, checking other party's heartbeat time using local timeout value is incorrect, as we may replace a valid lock (and the other party will delete ours on release).
- Added TTL indexes to all sets, so they will be automatically cleaned up by Mongo server. We might remove `ExpirationManager` now.
- Switched `MongoDistributedLock` implementation to using combined event + poll model, it doesn't actually require many changes.

**Comment by MarLoe** [comment]
@pieceofsummer I would really like to see you improvements to MongoDistributedLock. Could you paste here or can I see it in a fork/pull request?

**Comment by pieceofsummer** [comment]
@MarLoe sorry for the late reply, I'm quite busy with another project right now. 

But I'm starting to use MongoDB + Hangfire for my next project, so will definitely publish all my changes as PRs soon.

**Comment by MarLoe** [comment]
Welcome back @pieceofsummer ;)

As you can see I have taken some of your suggestions and implemented them already.

**Comment by pieceofsummer** [comment]
Great, I'm going to take a look at them!

I'm also considering to replace `int` to `ObjectId` everywhere (JobId, JobQueue etc.). It will save us half the number of insertion requests, but could (but not necessary will, need to check) break compatibility with old data. What do you think?

**Comment by MarLoe** [comment]
Breaking backwards compatibility should always be done with care.

Looking at Hangfire, some interfaces are marked obsolete and to be removed in version 2.0. This indicates to me that a version 2.0 is (somewhat) planned and that might be the perfect time to include any breaking changes.

**Comment by pieceofsummer** [comment]
It seems I've got a little distracted from the original distributed lock thing and ended up completely rewriting most of the queries :) to minimize data flow, so most aggregations are done on server instead of fetching all data to process on client. Also there's no extra roundtrips to generate job identifiers and get server time anymore. But it is still far from being optimal, I'm still working on it.

You can track the changes here: https://github.com/pieceofsummer/Hangfire.Mongo/tree/optimize-mongo

It changes the original data model a lot, so it's probably reasonable to release this as a separate package rather than merging into the original one.

**Pull request merged**
