### PR TITLE
Add support for specifying the database name in the connection string

### PR DESCRIPTION
**Pull request by 0xced**
I added the `[Obsolete]` attribute on the `UseMongoStorage` methods taking both a connection string and a database name.

### CODE REVIEW

**Comment by gottscj** [comment]
Also,

I will quickly create a 0.6.6 branch and merge this into that.

**Comment by 0xced** [comment]
> What do you think about having one overload where db name is explicitly set?
> That way clients using that functionality would not get an error.

Actually, it's still possible to use the overloads with the separate database name parameter. I just added the `Obsolete` attribute because I think it's preferable to have the database name in the connection string.

I think it's simpler if there's one recommended way to configure the connection but if you think they should not be marked obsolete, feel free to remove the attribute.

> I will quickly create a 0.6.6 branch and merge this into that.

Excellent, please go ahead. 👍

**Comment by gottscj** [comment]
thanks!

**Comment by imperugo** [comment]
I'm not sure is a good idea to mark the old method as obsolete.
I could have a single connection string with multiple database (in fact in my projects I've only one connection string in the entire solution),

Using your approach it means have 1 connection string for hangfire and another one for the other projects and the only difference is the db name.

From my point of view could be a good idea to use the dbname into the connection string, but also allow the user to force the db name from code.

**Pull request merged**
